require:
  # - rubocop-rspec
  - rubocop-rails
  # - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/*"
    - "script/**/*"
    - "log/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "vendor/**/*"
    - "lib/**/*"
    - "node_modules/**/*"
    - "db/seeders/*"
    - ".git/**/*"

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
    - "app/models/ability.rb"

Style/MixinUsage:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/*"
    - "config/initializers/*"
    - "app/models/ability.rb"

Metrics/AbcSize:
  Max: 18
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - "to"
    - "at"

Rails/EnvironmentVariableAccess:
  AllowReads: true

Style/GlobalVars:
  Exclude:
    - "app/services/cache_store_config_service.rb"
    - "config/initializers/redis.rb"
    - "config/initializers/sidekiq.rb"

Style/SymbolProc:
  Enabled: false

Style/SafeNavigationChainLength:
  Max: 3

# TODO: bug with false positives
Lint/UnusedMethodArgument:
  Enabled: false

# TODO: bug with false positives
Style/RedundantDoubleSplatHashBraces:
  Enabled: false

# TODO: bug
Rails/UniqueValidationWithoutIndex:
  Enabled: false
