plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "script/**/*"
    - "log/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "db/schema.rb"
    - "db/migrate/*_init_schema.rb"
    - "vendor/**/*"
    - "lib/**/*"
    - "node_modules/**/*"
    - "local/**/*"
    - ".git/**/*"

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^(\s*#)']

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
    - "app/models/ability.rb"

Style/MixinUsage:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/*"
    - "config/initializers/*"
    - "app/models/ability.rb"

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - "to"
    - "at"
    - "as"

Rails/EnvironmentVariableAccess:
  AllowReads: true

Style/GlobalVars:
  Exclude:
    - "app/services/cache_store_config_service.rb"
    - "config/initializers/redis.rb"

Style/SafeNavigationChainLength:
  Max: 3

RSpec/ImplicitSubject:
  Enabled: false 

RSpec/InstanceVariable:
  Exclude:
    - "spec/features/booking/**/*_spec.rb"

RSpec/MultipleMemoizedHelpers:
  Max: 10
  Exclude:
    - "spec/features/booking/**/*_spec.rb"

RSpec/NestedGroups:
  Max: 4
  Exclude:
    - "spec/domain/booking_flows/*_spec.rb"

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength: 
  Max: 10

# TODO: bug with false positives
Style/SymbolProc:
  Enabled: false

# TODO: bug with false positives
Lint/UnusedMethodArgument:
  Enabled: false

# TODO: bug with false positives
Style/RedundantDoubleSplatHashBraces:
  Enabled: false

# TODO: bug
Rails/UniqueValidationWithoutIndex:
  Enabled: false


RSpec/PendingWithoutReason:
  Enabled: false

