# config/schedule.yml

transition_booking_states:
  cron: "0 * * * *"
  class: TransitionBookingStatesJob
  queue: default

clean_data_digests:
  cron: "0 3 * * *"
  class: CleanDataDigestsJob
  queue: default

schedule_plan_b_backups:
  cron: "0 2 * * *"
  class: SchedulePlanBBackupsJob
  queue: default
