# config/schedule.yml

transition_booking_states:
  cron: "0 * * * *"
  class: TransitionBookingStatesJob
  queue: default

clean_data_digests:
  cron: "0 3 * * *"
  class: CleanDataDigestsJob
  queue: default

clean_data_digests:
  cron: "0 0 * * *"
  class: PlanBBackupJob
  queue: default


