---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimv-jobs
  annotations:
    keel.sh/match-tag: "true"
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimv-jobs
  template:
    metadata:
      labels:
        app: heimv-jobs
    spec:
      containers:
        - name: heimv
          image: ghcr.io/diegosteiner/heimv:main
          imagePullPolicy: Always
          command:
            - bin/jobs
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: app-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: url
          resources:
            requests:
              memory: 1024M
            limits:
              memory: 2048M
      restartPolicy: Always
