apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web.yaml
  - jobs.yaml

images:
  - name: ghcr.io/diegosteiner/heimv
    newTag: main

replicas:
  - name: heimv-jobs
    count: 1
  - name: heimv-web
    count: 2

secretGenerator:
  - name: app-secret
    # behavior: merge
    literals:
      - S3_ACCESS_KEY_ID=
      - S3_BUCKET_NAME=
      - S3_ENDPOINT=
      - S3_REGION=
      - S3_SECRET_ACCESS_KEY=
      - SECRET_KEY_BASE=
      - SMTP_SETTINGS=
  - name: database-secret
    literals:
      - password=
      - username=
      - host=
      - port=5432
      - database=
      - url=postgres://

configMapGenerator:
  - name: app-config
    literals:
      - APP_HOST=
      - EXCEPTION_RECIPIENTS=info@heimv.ch
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - REDIS_URL=redis://redis-service/0
      - MAIL_FROM=
      - PRIVACY_STATEMENT_URL=https://www.heimv.ch/privacy/
