---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimv-web
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimv-web
  template:
    metadata:
      labels:
        app: heimv-web
    spec:
      containers:
        - name: heimv
          image: ghcr.io/diegosteiner/heimv:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: app-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: url
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          resources:
            requests:
              memory: 512M
            limits:
              memory: 1024M
      initContainers:
        - name: heimv-migrate
          image: ghcr.io/diegosteiner/heimv:main
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: url
          resources:
            requests:
              memory: 512M
            limits:
              memory: 1024M
          imagePullPolicy: Always
          command:
            - "bin/rails"
            - "db:migrate"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: heimv-web-service
spec:
  ports:
    - port: 3000
  selector:
    app: heimv-web
