  cancel!-->cancelled
  set_provisional!-->provisional_request
  set_definitive!-->definitive_request
  extend_deadline!-->provisional_request
  register_payment!-->if3
  issue_contract!-->confirmed
  register_contract_signed!-->if3
  register_payment2!-->if5
  register_contract_signed2!-->if5
  cancel!-->payment_due
  issue_handover_protocol!-->upcoming
  issue_bill!-->payment_due
  register_payment3!-->if7
  register_payment4!-->if8
  write_off!-->completed

  initial-->new_request
  overdue_request-->cancelled
  new_request-->cancelled
  new_request-->provisional_request
  new_request-->definitive_request
  initial-->provisional_request
  overdue_request-->definitive_request
  provisional_request-->definitive_request
  provisional_request-->cancelled
  initial-->definitive_request
  definitive_request-->cancelled
  overdue_request-->provisional_request
  definitive_request-->confirmed
  confirmed-->confirmed
  confirmed-->cancelled
  overdue-->cancelled
  upcoming-->cancelled
  upcoming-->upcoming
  upcoming-->active
  active-->past
  past-->payment_due
  payment_due-->payment_due
  payment_due-->completed
  payment_overdue-->payment_overdue
  payment_overdue-->completed

  confirmed-->|if contracts.all?(&:signed?) && bills.deposits.all?(&:payed_or_prolonged?)|upcoming
  payment_due-->|if bills.all?(&:payed_or_written_off)|completed
  overdue-->|if (same as above)|upcoming
  payment_overdue-->|if (same as above)|completed

  provisional_request-->|if now > request_deadline|overdue_request
  overdue_request-->|if now > overdue_request_deadline|cancelled
  confirmed-->|if now > confirm_deadline|overdue
  payment_due-->|if bills.open.any? { |bill| now > bill.payment_deadline }|payment_overdue

  provisional_request-->if1
  overdue_request-->if2
  confirmed-->if3
  confirmed-->if4
  overdue-->if5
  payment_due-->if6
  payment_due-->if7
  payment_overdue-->if8
  if1-->overdue_request
  if1-->provisional_request
  if2-->overdue_request
  if2-->cancelled
  if3-->confirmed
  if3-->upcoming
  if4-->overdue
  if4-->confirmed
  if5-->overdue
  if5-->upcoming
  if6-->payment_due
  if6-->payment_overdue
  if7-->completed
  if7-->payment_due
  if8-->completed
  if8-->payment_overdue
