graph TD;

%% States
new_request(Neue Mietanfrage)
provisional_request(Provisorische Mietanfrage)
definitive_request(Definitive Mietanfrage)
overdue_request(Überfällige Mietanfrage)
cancelled(Annulierte Reservation)
cancelled2(Annulierte Reservation)
confirmed(Bestätigte Reservation)
upcoming(Geplante Belegung)
overdue(Überfällige Reservation)
active(Aktive Belegung)
past(Durchgeführte Belegung)
payment_due(Rechnung ausstehend)
payment_overdue(Rechnung überfällig)
completed(Abgeschlossene Belegung)

%% Actions
cancel![Annulieren]
cancel2![Annulieren]
cancel3![Annulieren]
set_provisional![Mietanfrage provisorisch setzen]
set_definitive![Mietanfrage definitiv setzen]
extend_deadline![Frist verlängern]
register_payment![Zahlungseingang registrieren]
register_payment2![Zahlungseingang registrieren]
register_payment3![Zahlungseingang registrieren]
register_payment4![Zahlungseingang registrieren]
register_contract_signed![Vertragserhalt registrieren]
register_contract_signed2![Vertragserhalt registrieren]
issue_contract![Vertrag ausstellen]
issue_handover_protocol![Übergabeprotokoll ausstellen]
issue_bill![Rechnung ausstellen]
write_off![Ausstand abschreiben]

%% Helpers
start1((start))
start2((start))
start3((start))
always((immer))
if1{1}
if2{2}
end1((ende))
end2((ende))
end3((ende))
if3{3}
if4{4}
if5{5}
if6{6}
if7{7}
if8{8}

subgraph Mietanfrage
  start1-->new_request
  overdue_request-->cancel!
  new_request-->cancel!
  new_request-->set_provisional!
  set_provisional!-->provisional_request
  new_request-->set_definitive!
  start2-->provisional_request
  provisional_request-->|System prüft Mietanfrage|if1
  if1-->|ja|overdue_request
  if1-->|nein|provisional_request
  overdue_request-->|Kunde bestätigt Mietanfrage|definitive_request
  provisional_request-->|Kunde bestätigt Mietanfrage|definitive_request
  provisional_request-->cancel!
  set_definitive!-->definitive_request
  start3-->definitive_request
  definitive_request-->cancel!
  overdue_request-->extend_deadline!
  extend_deadline!-->provisional_request
  overdue_request-->|System prüft Mietanfrage|if2
  if2-->|nein|overdue_request
  if2-->|ja|cancelled
  cancel!-->cancelled
  cancelled-->end1
end

subgraph Vertragsausstellung
  definitive_request-->issue_contract!
  issue_contract!-->confirmed
  confirmed-->|Verwalter modifiziert Reservation|confirmed
  confirmed-->cancel2!
  cancel2!-->cancelled2
  cancelled2-->end2
  confirmed-->register_payment!
  register_payment!-->if3
  confirmed-->register_contract_signed!
  register_contract_signed!-->if3
  confirmed-->|Kunde bestätigt Anzahlung|if3
  if3-->|nein|confirmed
  if3-->|ja|upcoming
  confirmed-->|System prüft bestätigte Reservation|if4
  if4-->overdue
  if4-->confirmed
  overdue-->register_payment2!
  register_payment2!-->if5
  overdue-->register_contract_signed2!
  register_contract_signed2!-->if5
  overdue-->|Kunde bestätigt Anzahlung|if5
  if5-->|nein|overdue
  if5-->|ja|upcoming
  overdue-->cancel2!
end

upcoming-->cancel3!
cancel3!-->payment_due

subgraph Durchführung
  upcoming-->issue_handover_protocol!
  issue_handover_protocol!-->upcoming
  upcoming-->|System aktiviert Belegung|active
  active-->|System beendet Belegung|past
end

subgraph Abrechnung
  past-->issue_bill!
  issue_bill!-->payment_due
  payment_due-->issue_bill!
  payment_due-->register_payment3!
  payment_due-->|System prüft Zahlungsausstände|if6
  if6-->payment_due
  if6-->payment_overdue
  payment_due-->register_payment3!
  payment_due-->write_off!
  register_payment3!-->if7
  if7-->|ja|completed
  if7-->|nein|payment_due
  payment_overdue-->register_payment4!
  payment_overdue-->|Verwalter moniert ausstehende Zahlung|payment_overdue
  payment_overdue-->write_off!
  if8-->|ja|completed
  if8-->|nein|payment_overdue
  register_payment4!-->if8
  write_off!-->completed
  completed-->end3
end


style start1 fill:#aaa,stroke:#000;
style start2 fill:#aaa,stroke:#000;
style start3 fill:#aaa,stroke:#000;
style if1  fill:#ccc,stroke:#000;
style if2  fill:#ccc,stroke:#000;
style if3  fill:#ccc,stroke:#000;
style if4  fill:#ccc,stroke:#000;
style if5  fill:#ccc,stroke:#000;
style if6  fill:#ccc,stroke:#000;
style if7  fill:#ccc,stroke:#000;
style if8  fill:#ccc,stroke:#000;
style end1  fill:#aaa,stroke:#000;
style end2  fill:#aaa,stroke:#000;
style end3  fill:#aaa,stroke:#000;

style new_request fill:#9CADBF,stroke:#496684;
style provisional_request fill:#9CADBF,stroke:#496684;
style definitive_request fill:#9CADBF,stroke:#496684;
style overdue_request fill:#9CADBF,stroke:#496684;
style cancelled fill:#9CADBF,stroke:#496684;
style cancelled2 fill:#9CADBF,stroke:#496684;
style confirmed fill:#9CADBF,stroke:#496684;
style upcoming fill:#9CADBF,stroke:#496684;
style overdue fill:#9CADBF,stroke:#496684;
style active fill:#9CADBF,stroke:#496684;
style past fill:#9CADBF,stroke:#496684;
style payment_due fill:#9CADBF,stroke:#496684;
style payment_overdue fill:#9CADBF,stroke:#496684;
style completed fill:#9CADBF,stroke:#496684;
