---
name: Continous Integration - CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: buildx
        uses: docker/setup-buildx-action@master

      - name: update version
        run: |
          if [ "${GITHUB_REF_TYPE}" == "tag" ]; then
            echo "${GITHUB_REF_NAME}" > VERSION
          else
            ref=$(echo ${GITHUB_REF#refs/heads/})
            sha=$(echo ${GITHUB_SHA} | cut -c1-7)
            echo "${ref} @${sha}" >> VERSION
          fi

      - name: docker build test
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          target: test
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: docker build target
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          target: production
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
  check:
    needs: 
      - build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: prepare artifacts
        run: mkdir -p artifacts

      - name: docker build test
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          target: test
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-test
          cache-from: type=gha

      - name: docker build target
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          target: production
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=gha
      
      - name: migrate
        run: docker compose --file docker-compose.ci.yml run e2e_target bin/rails db:drop db:create db:migrate

      - name: migrate
        run: docker compose --file docker-compose.ci.yml up -d e2e_target

      - name: bin/ci
        run: docker compose --file docker-compose.ci.yml run e2e_test bin/ci

      - if: failure()
        name: dump log
        run: docker compose --file docker-compose.ci.yml logs > ./artifacts/docker-compose.ci.log

      - if: failure()
        name: dump tmp
        run: docker cp $(docker compose --file docker-compose.ci.yml ps -qa e2e_test | head -n1):/rails/tmp ./artifacts/tmp

      - if: failure()
        name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts

  push:
    if: github.event_name != 'pull_request'
    needs: 
      - build
      - check
    steps:
      - name: buildx
        uses: docker/setup-buildx-action@master

      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build target
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: true
          target: production
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

