---
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p artifacts

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true

      - run: docker-compose --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache --project-directory . --file .github/docker-compose.yml build e2e_test

      - if: success()
        run: "docker-compose --project-directory . --file .github/docker-compose.yml run e2e_test bin/rails db:drop db:create db:migrate"

      - if: success()
        run: docker-compose --project-directory . --file .github/docker-compose.yml run e2e_test bin/check

      - if: success() && !github.base_ref
        run: "docker tag heimv:latest docker.pkg.github.com/diegosteiner/heimv/heimv:${GITHUB_REF##*/} && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true"

      - if: failure()
        run: docker-compose --project-directory . --file .github/docker-compose.yml logs e2e_target > ./artifacts/e2e_target.log

      - if: failure()
        run: cp -r tmp/capybara ./artifacts/

      - if: failure()
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts

      - run: docker tag heimv docker.pkg.github.com/diegosteiner/heimv/build-cache && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true

      # - uses: actions-hub/docker/login@master
      #   if: success()
      #   env:
      #     DOCKER_USERNAME: ${{ github.actor }}
      #     DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      #     DOCKER_REGISTRY_URL: docker.pkg.github.com

      # - name: Push to docker hub :latest
      #   if: success() && !github.base_ref
      #   uses: actions-hub/docker@master
      #   with:
      #     args: push docker.pkg.github.com/diegosteiner/heimv/heimv:${GITHUB_REF##*/}
