---
name: Continous Integration - CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - run: mkdir -p artifacts
        name: prepare artifacts

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        name: docker login

      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/heimv-e2e-test || true
        name: docker pull

      - run: docker-compose --project-directory . --file .github/docker-compose.yml build e2e_test
        name: docker build e2e_test

      - run: docker-compose --project-directory . --file .github/docker-compose.yml build e2e_target
        name: docker build e2e_target

      - run: docker tag heimv-e2e_test docker.pkg.github.com/$GITHUB_REPOSITORY/heimv-e2e_test && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/heimv-e2e_test || true
        name: docker push cache

      - name: migrate
        run: docker-compose --project-directory . --file .github/docker-compose.yml run e2e_target bin/rails db:drop db:create db:migrate

      - name: bin/check
        run: docker-compose --project-directory . --file .github/docker-compose.yml run e2e_test bin/check

      - if: success() && !github.base_ref
        name: docker push
        run: docker tag heimv-e2e_target docker.pkg.github.com/$GITHUB_REPOSITORY/heimv:latest && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/heimv:latest || true

      - if: failure()
        name: dump log
        run: docker-compose --project-directory . --file .github/docker-compose.yml logs e2e_target > ./artifacts/e2e_target.log

      - if: failure()
        name: dump screenshots
        run: cp -r tmp/capybara ./artifacts/

      - if: failure()
        name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts

      # - uses: actions-hub/docker/login@master
      #   if: success()
      #   env:
      #     DOCKER_USERNAME: ${{ github.actor }}
      #     DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      #     DOCKER_REGISTRY_URL: docker.pkg.github.com

      # - name: Push to docker hub :latest
      #   if: success() && !github.base_ref
      #   uses: actions-hub/docker@master
      #   with:
      #     args: push docker.pkg.github.com/diegosteiner/heimv/heimv:${GITHUB_REF##*/}
