---
name: Continous Integration - CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSE_PROJECT_NAME: heimv
  COMPOSE_FILE: docker-compose.ci.yml
  TARGET_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  TEST_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: update version
        run: |
          export VERSION="$(cat ./VERSION)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          ref=$(echo ${GITHUB_REF#refs/heads/})
          sha=$(echo ${GITHUB_SHA} | cut -c1-7)
          echo " ${ref}@${sha}" >> ./VERSION

      - name: docker login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        run: |
          docker buildx bake -f docker-compose.ci.yml e2e_test e2e_target \
            --push \
            --set e2e_test.tags=$TEST_IMAGE \
            --set e2e_target.tags=$TARGET_IMAGE \
            --set e2e_test.cache-from=type=gha,scope=e2e_test \
            --set e2e_test.cache-to=type=gha,mode=max,scope=e2e_test \
            --set e2e_target.cache-from=type=gha,scope=e2e_target \
            --set e2e_target.cache-to=type=gha,mode=max,scope=e2e_target

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: docker login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pull and retag for local use
        run: |
          docker pull $TEST_IMAGE
          docker pull $TARGET_IMAGE
          docker tag $TEST_IMAGE   heimv-e2e_test:latest
          docker tag $TARGET_IMAGE heimv-e2e_target:latest

      - name: run unit specs
        run: docker compose run e2e_test bin/check_ci
      # - if: always()
      #   name: stop
      #   run: docker compose down --remove-orphans
      # - if: failure()
      #   name: cancel workflow on failure
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.actions.cancelWorkflowRun({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         run_id: context.runId
      #       })

  e2e:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        browser:
          - name: chrome
            selenium_image: selenium/standalone-chrome
          - name: firefox
            selenium_image: selenium/standalone-firefox
    env:
      COMPOSE_PROJECT_NAME: heimv-${{ matrix.browser.name }}
      SELENIUM_IMAGE: ${{ matrix.browser.selenium_image }}
      SELENIUM_BROWSER: ${{ matrix.browser.name }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: docker login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pull images
        run: |
          docker pull $TEST_IMAGE
          docker pull $TARGET_IMAGE
          docker tag $TEST_IMAGE   heimv-${{ matrix.browser.name }}-e2e_test:latest
          docker tag $TARGET_IMAGE heimv-${{ matrix.browser.name }}-e2e_target:latest

      - name: run e2e specs
        run: |
          mkdir -p videos
          docker compose run e2e_target bin/rails db:migrate
          docker compose up --wait e2e_target
          docker compose run e2e_test bin/rspec ./spec --tag @type:feature --fail-fast

      - if: failure()
        name: prepare artifacts
        run: |
          mkdir -p artifacts
          docker compose logs > ./artifacts/docker-compose.ci.log
          docker cp $(docker compose ps -qa e2e_test | tail -n1):/rails/tmp/capybara ./artifacts/

      - if: failure()
        name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-${{ matrix.browser.name }}
          path: artifacts
      # - if: always()
      #   name: stop
      #   run: docker compose down --remove-orphans

  release:
    runs-on: ubuntu-latest
    needs: e2e
    if: github.event_name != 'pull_request'
    env:
      TARGET_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
      REF_IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: update version
        run: |
          export VERSION="$(cat ./VERSION)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: docker login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push image
        run: |
          docker pull $TARGET_IMAGE
          docker tag $TARGET_IMAGE $REF_IMAGE
          docker push $REF_IMAGE

      - if: github.ref == 'refs/heads/main'
        name: push versioned image
        run: |
          docker tag $TARGET_IMAGE ghcr.io/${{ github.repository }}:$VERSION
          docker push ghcr.io/${{ github.repository }}:$VERSION

  cleanup:
    runs-on: ubuntu-latest
    if: always()
    needs: [ build, e2e, release ]
    permissions:
      packages: write
    steps:
      - name: Delete build images
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          container: ${{ github.event.repository.name }}
          prune-tags-regexes: |
            ^${{ github.sha }}(-test)?$
