---
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - run: mkdir -p artifacts
        name: prepare artifacts

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        name: docker login

      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
        name: docker pull

      - run: docker-compose --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache --project-directory . --file .github/docker-compose.yml build e2e_test
        name: docker build

