---
name: Continous Integration - CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: docker/setup-buildx-action@master
        name: buildx

      - run: mkdir -p artifacts
        name: prepare artifacts

      - uses: docker/login-action@v1
        name: docker login
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        name: docker build e2e_test
        with:
          load: true
          push: false
          target: build
          builder: ${{ steps.buildx.outputs.name }}
          tags: ghcr.io/diegosteiner/heimv:e2e_test
          cache-from: type=registry,ref=ghcr.io/diegosteiner/heimv:e2e_test-buildcache
          cache-to: type=registry,ref=ghcr.io/diegosteiner/heimv:e2e_test-buildcache,mode=max

      - uses: docker/build-push-action@v2
        name: docker build e2e_target
        with:
          load: true
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          tags: ghcr.io/diegosteiner/heimv:latest
          cache-from: type=registry,ref=ghcr.io/diegosteiner/heimv:latest-buildcache
          cache-to: type=registry,ref=ghcr.io/diegosteiner/heimv:latest-buildcache,mode=max

      # - run: docker compose --file docker-compose.ci.yml build
      #   name: docker build

      - run: docker compose version
      - run: docker image ls

      - run: docker compose --file docker-compose.ci.yml run e2e_target bin/rails db:drop db:create db:migrate
        name: migrate

      - run: docker compose --file docker-compose.ci.yml run e2e_test bin/check
        name: bin/check

      - uses: docker/build-push-action@v2
        name: docker push
        with:
          load: true
          push: ${{ github.event_name != 'pull_request' }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ghcr.io/diegosteiner/heimv:${{ github.head_ref }}

      - if: failure()
        name: dump log
        run: docker compose --file docker-compose.ci.yml logs e2e_target > ./artifacts/e2e_target.log

      - if: failure()
        name: dump screenshots
        run: cp -r tmp/capybara ./artifacts/

      - if: failure()
        name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts
