---
name: Update Release Version

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tag
        run: |
          echo "${{ github.event.release.tag_name }}" > VERSION
          git tag -a "${{ github.event.release.tag_name }}" -m "chore: Release ${{ github.event.release.tag_name }}"
          git push origin "${{ github.event.release.tag_name }} {{ github.ref_name }} "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
